Better parsing of command line arguments, using getopt Online --help Updates in README

diff --git a/thea-backup b/thea-backup
--- a/thea-backup
+++ b/thea-backup
@@ -2,15 +2,34 @@
 # THEA BACKUP SCRIPTS
 # 
 # Make a backup
+# Exit codes:
+# 0	Backup completed successfully
+# 1	Could not mount backup volume
+# 2	Backup command failed
+# 3	Could not unmount backup volume
+# 9	Could not parse arguments
 
 source /usr/local/share/thea/config
 source /usr/local/share/thea/functions
+
+function usage()
+{
+	usage_pre
+	echof "Make a backup" "heading"
+	echof "Usage: thea-backup [options] [postact]" "info"
+	echof "If postact is 'andsleep', the computer will be suspended after backing up" "info"
+	echof "If postact is 'andpoweroff', the computer will be powered off" "info"
+	echof "If postact is 'andpause', the user will be prompted to press ENTER to exit" "info"
+	usage_post
+	exit 9
+}
 
 echof_date=0
 echof_silent=0
 echof_color=1
 
 maybe_disable_color
+parseargs ${0} ${@}
 
 set_term_title "Backup"
 
@@ -45,18 +64,17 @@ then
 	exit 3 
 fi
 
-if [ ".${1}" = ".andsleep" ]
+if [ ".${params[1]}" = ".andsleep" ]
 then
 	sudo ${SUSPEND_CMD} ${SUSPEND_CMD_ARGS}
 	press_to_exit
-elif [ ".${1}" = ".andpoweroff" ]
+elif [ ".${params[1]}" = ".andpoweroff" ]
 then
 	sudo ${POWEROFF_CMD} ${POWEROFF_CMD_ARGS}
 	press_to_exit
-elif [ ".${1}" = ".andpause" ]
+elif [ ".${params[1]}" = ".andpause" ]
 then
 	press_to_exit
 fi
-
 
 exit 0
diff --git a/thea-diff b/thea-diff
--- a/thea-diff
+++ b/thea-diff
@@ -2,22 +2,34 @@
 # THEA BACKUP SCRIPTS
 # 
 # Search for differences between a file and a backed up version of the same file
+# Exit codes:
+# 0	Differences printed successfully
+# 1	Error occured while printing differences
+# 9	Could not parse arguments
 
 source /usr/local/share/thea/config
 source /usr/local/share/thea/functions
+
+function usage()
+{
+	usage_pre
+	echof "Search for differences between a file and a backed up version of the same file" "heading"
+	echof "Usage: thea-diff [options] <filename> <snapshot number>" "info"
+	echof "Snapshot number must be smaller than ${RSNAPSHOT_SNAPSHOTS}" "info"
+	usage_post
+	exit 9
+}
 
 echof_date=0
 echof_silent=0
 echof_color=1
 
 maybe_disable_color
+parseargs ${0} ${@}
 
-if [[ "."${1} = "." || "."${2} = "." || ! "${2}" =~ "^[0-9]+$" || ${2} -ge ${RSNAPSHOT_SNAPSHOTS} ]]
+if [[ "."${params[1]} = "." || "."${params[2]} = "." || ! "${params[2]}" =~ "^[0-9]+$" || ${params[2]} -ge ${RSNAPSHOT_SNAPSHOTS} ]]
 then
-	echof "Required arguments are missing or invalid" "error"
-	echof "Usage: thea-diff <filename> <snapshot number>" "info"
-	echof "Snapshot number must be smaller than ${RSNAPSHOT_SNAPSHOTS}" "info"
-	exit 1
+	usage
 fi
 
 check_if_mounted
@@ -28,7 +40,7 @@ then
 	exit 1
 fi
 
-do_diff "${1}" ${2}
+do_diff "${params[1]}" ${params[2]}
 if [ $? -eq 5 ]
 then
 	exit 1
diff --git a/thea-gui-mount b/thea-gui-mount
--- a/thea-gui-mount
+++ b/thea-gui-mount
@@ -2,10 +2,24 @@
 # THEA BACKUP SCRIPTS
 # 
 # Mount the backup volume - to be launched via a GUI button
-# Note: This script actually runs thea-mount
+# Exit codes:
+# 0	The command was completed
+# 8	Not in GUI
+# 9	Could not parse arguments
 
 source /usr/local/share/thea/config
 source /usr/local/share/thea/functions
+
+function usage()
+{
+	usage_pre
+	echof "Mount the backup volume" "heading"
+	echof "Usage: thea-gui-mount [options] [postact]" "info"
+	echof "This program should only be launched from within the GUI" "info"
+	echof "If postact is 'andopen', the backup volume will be opened after mounting" "info"
+	usage_post
+	exit 9
+}
 
 check_gui
 
@@ -14,6 +28,7 @@ echof_silent=1
 echof_color=1
 
 maybe_disable_color
+parseargs ${0} ${@}
 
 (
 	echo "10"
@@ -46,7 +61,7 @@ maybe_disable_color
 			--text="Unable to mount backup volume ${BACKUP_VOLUME}"
 	fi
 
-	if [[ "."${1} = ".andopen" && ${success} -eq 1 ]]
+	if [[ "."${params[1]} = ".andopen" && ${success} -eq 1 ]]
 	then
 		xdg-open ${BACKUP_VOLUME}
 	fi
diff --git a/thea-restore b/thea-restore
--- a/thea-restore
+++ b/thea-restore
@@ -2,22 +2,35 @@
 # THEA BACKUP SCRIPTS
 # 
 # Restore a file from backup
+# Exit codes:
+# 0	File restored successfully
+# 1	Unable to restore the file specified
+# 2	Error while restoring
+# 9	Could not parse arguments
 
 source /usr/local/share/thea/config
 source /usr/local/share/thea/functions
+
+function usage()
+{
+	usage_pre
+	echof "Restore a file from backup" "heading"
+	echof "Usage: thea-restore [options] <filename> <snapshot number>" "info"
+	echof "Snapshot number must be smaller than ${RSNAPSHOT_SNAPSHOTS}" "info"
+	usage_post
+	exit 9
+}
 
 echof_date=0
 echof_silent=0
 echof_color=1
 
 maybe_disable_color
+parseargs ${0} ${@}
 
-if [[ "."${1} = "." || "."${2} = "." || ! "${2}" =~ "^[0-9]+$" || ${2} -ge ${RSNAPSHOT_SNAPSHOTS} ]]
+if [[ "."${params[1]} = "." || "."${params[2]} = "." || ! "${params[2]}" =~ "^[0-9]+$" || ${params[2]} -ge ${RSNAPSHOT_SNAPSHOTS} ]]
 then
-	echof "Required arguments are missing or invalid" "error"
-	echof "Usage: thea-restore <filename> <snapshot number>" "info"
-	echof "Snapshot number must be smaller than ${RSNAPSHOT_SNAPSHOTS}" "info"
-	exit 1
+	usage
 fi
 
 check_if_mounted
@@ -28,5 +41,5 @@ then
 	exit 1
 fi
 
-do_restore "${1}" ${2}
+do_restore "${params[1]}" ${params[2]}
 exit $?
diff --git a/thea-summary b/thea-summary
--- a/thea-summary
+++ b/thea-summary
@@ -2,21 +2,33 @@
 # THEA BACKUP SCRIPTS
 # 
 # Summarize the differences between a file and all its backed up versions
+# Exit codes:
+# 0	Summary printed successfully
+# 1	Error occured while printing summary
+# 9	Could not parse arguments
 
 source /usr/local/share/thea/config
 source /usr/local/share/thea/functions
+
+function usage()
+{
+	usage_pre
+	echof "Summarize the differences between a file and all its backed up versions" "heading"
+	echof "Usage: thea-summary [options] <filename>" "info"
+	usage_post
+	exit 9
+}
 
 echof_date=0
 echof_silent=0
 echof_color=1
 
 maybe_disable_color
+parseargs ${0} ${@}
 
-if [ "."${1} = "." ]
+if [ "."${params[1]} = "." ]
 then
-	echof "Required arguments are missing or invalid" "error"
-	echof "Usage: thea-summary <filename>" "info"
-	exit 1
+	usage
 fi
 
 check_if_mounted
@@ -27,5 +39,5 @@ then
 	exit 1
 fi
 
-do_summary "${1}"
+do_summary "${params[1]}"
 exit $?
